blank_issues_enabled: false
contact_links:
  - name: yiclashcore Community Support
    url: https://github.com/lingyicute/YiClashCore/discussions
    about: Please ask and answer questions about yiclashcore here.
